#!/bin/sh

ENABLED=yes

DESC="Tiny SNMP server"
PROCS="mini-snmpd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-i br0,eth0 -D super_router -L antarctida -C my@mail.com"
PREARGS=""

. /opt/etc/init.d/rc.func
