#!/bin/sh

ENABLED=yes

DESC="PHP FPM"
PROCS="php8-fpm"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-D -y /opt/etc/$PROCS.conf -g $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
