#!/bin/sh

ENABLED=yes

DESC="PHP FastCGI"
PROCS="php8-fcgi"
PROG="/opt/bin/$PROCS"

{ [ -f "/opt/etc/php8/php8-fastcgi" ] && \
. /opt/etc/php8/php8-fastcgi ; } || \
{ printf "\033[1;31m %s \033[0m\n" "Abort: conf file not found." && exit 1 ; }

ARGS="-b $BIND"
PREARGS=""

. /opt/etc/init.d/rc.func
