#!/bin/sh

ENABLED=yes

DESC="Keepalived"
PROCS="keepalived"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-P -D -d -n -p $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
