#!/bin/sh

ENABLED=yes

DESC="Unbound daemon DNS resolver"
PROCS="unbound"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
  [ -d "/opt/var/lib/$PROCS" ] || {
    mkdir -pm 0750 /opt/var/lib/"$PROCS"
    chown -R "$PROCS":"$PROCS" /opt/var/lib/"$PROCS"
  }
}

PRECMD="pre_cmd"
ARGS="-c /opt/etc/$PROCS/$PROCS.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
