#!/bin/sh

ENABLED=yes
PROCS="sshd"
ARGS="-D"
PREARGS=""
DESC="OpenSSH"
PROG="/opt/sbin/$PROCS"
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
