#!/bin/sh

ENABLED=yes

DESC="OpenSSH"
PROCS="sshd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
  [ -d "/opt/var/empty" ] || mkdir -pm 0700 /opt/var/empty
}

PRECMD="pre_cmd"
ARGS="-D"
PREARGS=""

. /opt/etc/init.d/rc.func
