#!/bin/sh

ENABLED=yes

DESC="Transmission BitTorrent client"
PROCS="transmission-daemon"
PROG="/opt/bin/$PROCS"

TRANSMISSION_WEB_HOME="/opt/share/transmission/public_html"

ARGS="-g /opt/etc/transmission"
PREARGS=""

. /opt/etc/init.d/rc.func
