#!/bin/sh

ENABLED=yes

DESC="Redis server"
PROCS="redis-server"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/redis.pid"

pre_cmd() {
  rm -f "$PID_FILE"
  [ -d "/opt/var/lib/redis" ] || \
  mkdir -pm 0750 /opt/var/lib/redis
}

PRECMD="pre_cmd"
ARGS="/opt/etc/redis.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
