#!/bin/sh

ENABLED=yes

DESC="UPnP front-end to Music Player Daemon"
PROCS="upmpdcli"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-c /opt/etc/$PROCS.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
