#!/bin/sh

ENABLED=yes

DESC="DNSCrypt Proxy"
PROCS="dnscrypt-proxy"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-a 127.0.0.1:65053 -p $PID_FILE -d -R cisco"
PREARGS=""

. /opt/etc/init.d/rc.func
