#!/bin/sh

ENABLED=yes

DESC="System services monitor"
PROCS="monit"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-c /opt/etc/monitrc -d 120 -p $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
