#!/bin/sh

{ [ -d "/dev/snd" ] && ENABLED=yes ; } || ENABLED=no


DESC="Shairport Sync audio player"
PROCS="shairport-sync"
PROG="/opt/bin/$PROCS"

# software volume control
# output to: audio card 0 device 0
ARGS="-d  -- -d hw:0,0"

# Hi-Fi mode: hardware volume control
# output to: audio card 0 device 0
# note: you need to set proper mixer control name with -c option
# in case it have different name than PCM (use alsamixer to check)
# you can't control volume on digital SPDIF outputs in this mode
# ARGS="-d -- -d hw:0,0 -m hw:0 -t hardware -c PCM"
 
# useful options to add (see shairport-sync --help for more):
# --statistics : print some interesting statistics to log
# --verbose : print debug information; -vv more; -vvv lots

PREARGS=""

. /opt/etc/init.d/rc.func
