#!/bin/sh

ENABLED=yes
PROCS="mysqld"
PROG="/opt/bin/$PROCS"
ARGS=""
PREARGS=""
DESC="MariaDB"
LIMIT="20"
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
