#!/bin/sh

ENABLED=yes

DESC="Privoxy server"
PROCS="privoxy"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "PID_FILE"
}

PRECMD="pre_cmd"
ARGS="--pidfile $PID_FILE /opt/etc/$PROCS/config"
PREARGS=""

. /opt/etc/init.d/rc.func
