#!/bin/sh

ENABLED=yes

DESC="Autossh client"
PROCS="autossh"
PROG="/opt/sbin/$PROCS"

{ [ -f "/opt/etc/config/$PROCS.conf" ] && \
. /opt/etc/config/$PROCS.conf ; } || \
{ printf "\033[1;31m %s \033[0m\n" "Abort: conf file not found." && exit 1 ; }

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-f $SSH_ARGS"
PREARGS=""

. /opt/etc/init.d/rc.func
