#!/bin/sh

ENABLED=yes

DESC="Static secure identd"
PROCS="fakeidentd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-r"
PREARGS=""

. /opt/etc/init.d/rc.func
