#!/bin/sh

ENABLED=yes

DESC="GPS daemon"
PROCS="gpsd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-n -P $PID_FILE -S 2947 /dev/ttyUSB0"
PREARGS=""

. /opt/etc/init.d/rc.func
