#!/bin/sh

ENABLED=yes

DESC="Icecast streaming media server"
PROCS="icecast"
PROG="/opt/bin/$PROCS"

pre_cmd() {
  [ -d "/opt/var/log/$PROCS" ] || {
    mkdir -pm 0750 /opt/var/log/"$PROCS"
    chown "$PROCS":"$PROCS" /opt/var/log/"$PROCS"
  }
}

PRECMD="pre_cmd"
ARGS="-c /opt/etc/$PROCS.xml -b"
PREARGS=""

. /opt/etc/init.d/rc.func
