#!/bin/sh

ENABLED=yes

DESC="DNS Over HTTPS Proxy server"
PROCS="https-dns-proxy"
PROG="/opt/sbin/$PROCS"

{ [ -f "/opt/etc/config/$PROCS.conf" ] && . /opt/etc/config/$PROCS.conf ; } || \
{ printf "\033[1;31m %s \033[0m\n" "Abort: conf file not found." && exit 1 ; }

ARGS="$OPTIONS"
PREARGS=""

. /opt/etc/init.d/rc.func
