#!/bin/sh

ENABLED=yes

DESC="Samba AD-DC daemon"
PROCS="samba"
PROG="/opt/sbin/$PROCS"

pre_cmd() {
  for i in \
    /opt/var/cache/samba \
    /opt/var/lib/samba \
    /opt/var/lock/samba \
    /opt/var/log/samba \
    /opt/var/run/samba
  do
    [ -d "$i" ] || {
      mkdir -pm 0755 "$i"
    }
  done
}

PRECMD="pre_cmd"
ARGS="-D"
PREARGS=""

. /opt/etc/init.d/rc.func
