#!/bin/sh

ENABLED=yes
PROCS="znc"
PROG="/opt/bin/$PROCS"
ARGS="-d /opt/share/$PROCS -r"
PREARGS=""
PRECMD="chown -Rh $PROCS:$PROCS /opt/share/$PROCS /opt/var/run/$PROCS"
DESC="ZNC"

PID_FILE="/opt/var/run/$PROCS/$PROCS.pid"
SIGNAL="USR1"

. /opt/etc/init.d/rc.func
