#!/bin/sh

ENABLED=yes

DESC="GNU Krell Monitors Server"
PROCS="gkrellmd"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
}

PRECMD="pre_cmd"
ARGS="--pidfile $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
