#!/bin/sh

ENABLED=yes

DESC="uMurmur daemon"
PROCS="umurmurd"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-p $PID_FILE -c /opt/etc/umurmur.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
