#!/bin/sh

ENABLED=yes

DESC="Network bandwidth monitor"
PROCS="darkstat"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS/$PROCS.pid"

pre_cmd() {
  rm -f "$PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-i ppp0 --chroot /opt/var/empty --syslog"
PREARGS=""

. /opt/etc/init.d/rc.func
